const ROUTES = {
    BLOG: "/blog",
    ORDERS: "/",
    STOCKS: "/stocks",
    ANALYTICS: "/analytics",
    BLOG_CREATE: "/blog-create",
    STOCK_CREATE: "/stock-create",
    CITY: "/city",
    CITY_CREATE: "/city-create",
    SIGN_IN: "/sign-in",
    BLOG_DETAIL: "/blog-detail",
    CITY_DETAIL: "/city-detail",
    USERS: "/users",
    USERS_DETAIL: "/users-detail",
    ORDERS_DETAIL: "/orders-detail",
    WORK: "/work",
    WORK_CREATE: "/work-create",
    WORK_DETAIL: "/work-detail",
    TAGS: "/tags",
    TAGS_CREATE: "/tags-create",
    TAG_DETAIL: "/tag-detail",
    STOCK_DETAIL: "/stock-detail",
    PRODUCTS: "/products",
    PRODUCT_DETAIL: "/product-detail",
    CATALOG: "/catalog",
    CATALOG_CREATE: "/catalog-create",
    CATALOG_DETAIL: "/catalog-detail",
    ADVANTAGES: "/advantage",
    ADVANTAGES_CREATE: "/advantage-create",
    ADVANTAGES_DETAIL: "/advantage-detail",
};

export default ROUTES;
