const ROUTES = {
    AUTH: "/auth",
    BLOG: "/blog",
    ORDERS: "/orders",
    STOCKS: "/stocks",
    ANALYTICS: "/analytics",
    BLOG_CREATE: "/blog-create",
    STOCK_CREATE: "/stock-create",
    CITY: "/city",
    CITY_CREATE: "/city-create",
    SIGN_IN: "/",
    BLOG_DETAIL: "/blog-detail",
    CITY_DETAIL: "/city-detail",
    USERS: "/users",
    USERS_DETAIL: "/users-detail",
    ORDERS_DETAIL: "/orders-detail",
    WORK: "/work",
    WORK_CREATE: "/work-create",
    WORK_DETAIL: "/work-detail",
    TAGS: "/tags",
    TAGS_CREATE: "/tags-create",
    TAG_DETAIL: "/tag-detail",
};

export default ROUTES;
